# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Proyectos/Python/RenameShapeFiles/resources\diagRename.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(487, 254)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/imgBase/img/rename1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAnimated(False)
        MainWindow.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.line1 = QtWidgets.QLineEdit(self.centralwidget)
        self.line1.setGeometry(QtCore.QRect(20, 40, 331, 22))
        self.line1.setObjectName("line1")
        self.btn1 = QtWidgets.QPushButton(self.centralwidget)
        self.btn1.setGeometry(QtCore.QRect(370, 37, 93, 28))
        self.btn1.setObjectName("btn1")
        self.line2 = QtWidgets.QLineEdit(self.centralwidget)
        self.line2.setGeometry(QtCore.QRect(20, 160, 331, 22))
        self.line2.setObjectName("line2")
        self.lb1 = QtWidgets.QLabel(self.centralwidget)
        self.lb1.setGeometry(QtCore.QRect(20, 20, 321, 16))
        self.lb1.setObjectName("lb1")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 140, 321, 16))
        self.label.setObjectName("label")
        self.btn4 = QtWidgets.QPushButton(self.centralwidget)
        self.btn4.setGeometry(QtCore.QRect(270, 210, 93, 28))
        self.btn4.setObjectName("btn4")
        self.btn5 = QtWidgets.QPushButton(self.centralwidget)
        self.btn5.setGeometry(QtCore.QRect(370, 210, 93, 28))
        self.btn5.setObjectName("btn5")
        self.btn2 = QtWidgets.QPushButton(self.centralwidget)
        self.btn2.setGeometry(QtCore.QRect(20, 210, 93, 28))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/imgBase/img/info.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn2.setIcon(icon1)
        self.btn2.setObjectName("btn2")
        self.btn3 = QtWidgets.QPushButton(self.centralwidget)
        self.btn3.setGeometry(QtCore.QRect(120, 210, 93, 28))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/imgBase/img/dona.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn3.setIcon(icon2)
        self.btn3.setObjectName("btn3")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 80, 331, 16))
        self.label_2.setObjectName("label_2")
        self.cmb1 = QtWidgets.QComboBox(self.centralwidget)
        self.cmb1.setGeometry(QtCore.QRect(20, 100, 331, 22))
        self.cmb1.setObjectName("cmb1")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Renombrar archivos .shp"))
        self.btn1.setText(_translate("MainWindow", "..."))
        self.lb1.setText(_translate("MainWindow", "Selecciona la carpeta que contiene tus archivos .shp"))
        self.label.setText(_translate("MainWindow", "Ingresa el nuevo nombre"))
        self.btn4.setText(_translate("MainWindow", "Ejecutar"))
        self.btn5.setText(_translate("MainWindow", "Cancelar"))
        self.btn2.setText(_translate("MainWindow", "Renombrar"))
        self.btn3.setText(_translate("MainWindow", "Apoya"))
        self.label_2.setText(_translate("MainWindow", "Selecciona el archivo shapefile (.shp) a renombrar"))
import RenameShapeFiles.gui.resources
